### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by seveibar** [martinbeentjes/npm-get-version-action#1]
This looks like what I need, but I'm not sure how to use it. Could you give an example workflow file?

**Comment by martinbeentjes** [comment]
Thanks for using the Action! ❤️ 

I will supply an example when I am back at my machine. And also expand the README a bit ☺️

**Comment by martinbeentjes** [comment]
@seveibar I've added an example in the README. Is that sufficient?

**Comment by seveibar** [comment]
Perfect thank you!!!
