### ISSUE TITLE
The Mac fails to be executed

### ISSUE THREAD

**Issue by wforguo** [martinbeentjes/npm-get-version-action#12]
The Mac fails to be executed,how to resolve

**Comment by martinbeentjes** [comment]
What is failing? What error messages do you get? I can not help with only this vague information.

**Comment by tr3ysmith** [comment]
So github actions says that this action isn't supported on anything other than linux os.

Not sure why...

![image](https://user-images.githubusercontent.com/15764606/135318707-5f6dbeaf-d867-45f4-89d4-e4efe022d2ac.png)

**Comment by tr3ysmith** [comment]
For now, i'm executing this code manually on my mac runner:

echo ::set-output name=current-version::$(cat package.json | sed -n -e '/"version":/ s/^.*"\(.*\)".*/\1/p')
