### ISSUE TITLE
`jq: not found`

### ISSUE THREAD

**Issue by radovix** [martinbeentjes/npm-get-version-action#16]
I've started using [npm-get-version-action](https://github.com/martinbeentjes/npm-get-version-action) in one of my workflows yesterday. Today, I noticed that some changes in the `entrypoint.sh` were made and I'm not totally sure if my workflow is still not configured well or wether this change resulted in action no longer working properly. Anways, this is what I see in the logs of my workflow:

```
/entrypoint.sh: line 4: jq: not found
```

This is how I use the action (echo in the logs shows nothing):

```
- name: get-current-version
  id: current-version
  uses: martinbeentjes/npm-get-version-action@master

- name: logs
  run: |
      echo ${{ steps.current-version.outputs.current-version }}
```

**Comment by robbinjanssen** [comment]
I've created a PR to fix this: https://github.com/martinbeentjes/npm-get-version-action/pull/18
