### ISSUE TITLE
Release v1.2.0 provides error `unable to find version "master"`

### ISSUE THREAD

**Issue by mckrava** [martinbeentjes/npm-get-version-action#17]
After new release v1.2.0 I'm getting error in my actions:
```
Unable to resolve action `martinbeentjes/npm-get-version-action@master`, unable to find version `master`
```
Everything worked before this release.

**Comment by mckrava** [comment]
Looks like it's related issue - https://github.com/martinbeentjes/npm-get-version-action/issues/15

**Comment by ochikov** [comment]
Same here.

**Comment by martinbeentjes** [comment]
Fixed
