### ISSUE TITLE
Failed to download action 404

### ISSUE THREAD

**Issue by the-glima** [martinbeentjes/npm-get-version-action#2]
I've followed exactly your README adding:

```
- name: get-npm-version
   uses: martinbeentjes/npm-get-version-action@v1
```

But:

![image](https://user-images.githubusercontent.com/1394578/78465261-98bee800-76f3-11ea-85e2-5b43c8e5afd0.png)

**Comment by martinbeentjes** [comment]
Can you try with `@master`?

**Comment by anvar** [comment]
`@master` works!

**Comment by martinbeentjes** [comment]
@anvar Thanks, I've updated the README.md for now.
