### ISSUE TITLE
Unable to resolve action

### ISSUE THREAD

**Issue by ochikov** [martinbeentjes/npm-get-version-action#20]
After the new release, the github action can't resolve the package:
```
Unable to resolve action `martinbeentjes/npm-get-version-action@master`, unable to find version `master`
```

**Comment by martinbeentjes** [comment]
Fixed, I renamed the branch. Sorry for the inconvience.

**Comment by gion-andri** [comment]
@martinbeentjes Will the branch name remain `main` or are you reverting this change?

**Comment by martinbeentjes** [comment]
I noticed the issues this caused, I have temporarily added the branch back for a period of change. My apologies for all the pipelines that broke down.
