### ISSUE TITLE
Set output is now deprecated

### ISSUE THREAD

**Issue by ffjdm** [martinbeentjes/npm-get-version-action#24]
Hi,

The set-output command is now deprecated.

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:
> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by steliyan** [comment]
Can someone tag a new version with the fix?
