### ISSUE TITLE
The set-output command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by anuteresa** [martinbeentjes/npm-get-version-action#26]
This is causing the following annotation to show for any jobs using this action:

The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by anuteresa** [comment]
@martinbeentjes Can you please have a look into it?

**Comment by revrenlove** [comment]
@anuteresa
Instead of using `uses: martinbeentjes/npm-get-version-action@master`, using `uses: martinbeentjes/npm-get-version-action@main` seemed to fix this error. The `master` branch is still using old `set-output`, but the `main` branch is fine.

**Comment by martinbeentjes** [comment]
This is indeed fixed in the main branch. I will put some effort in making proper version tags next week. 

Thanks for notifying!

**Comment by mpatel-oaknorth** [comment]
@martinbeentjes Will there be a new version tags for this anytime soon? May 31st isn't too far off!

**Comment by martinbeentjes** [comment]
This is fixed with #25, and I have now updated the release to be a proper version instead of the branch name. Thanks for reminding me 🚀
