### ISSUE TITLE
Feature request: add working-directory key

### ISSUE THREAD

**Issue by remithomas** [martinbeentjes/npm-get-version-action#4]
- [x] Feature request

It should be a good feature to select the package dir by adding `add working-directory` key.

What do you think ?
thank you for the plugin !

**Comment by martinbeentjes** [comment]
@remithomas Thanks for the message! It is amazing to see people use something you created.

It is a good improvement to be able to point to the working directory, something to implement in the near future. Thanks for the issue!

**Comment by MarkoCen** [comment]
+1 awesome plugin
currently it can't be used with monorepo setup since each package in monorepo has its own package.json, adding `working-directory` should resolve this issue.

**Comment by jan-tee** [comment]
Just submitted a PR for this. I don't want to publish a custom version, please just integrate into yours and tag as a new version

**Comment by martinbeentjes** [comment]
Closed with #4
